language: cpp
compiler: 
    - clang
    - gcc
before_install:
    - sudo add-apt-repository ppa:george-edison55/cmake-3.x --yes
    - sudo apt-get update -qq
    - sudo apt-get install -qq cmake
script:
    - mkdir bld
    - cd bld/; cmake ../
    - make
    - ut
